CREATE DATABASE `caro`;
USE `caro`;
CREATE TABLE `caro`.`user`(
    `ID` VARCHAR(10) NOT NULL,
    `NAME` VARCHAR(20) NULL DEFAULT NULL,
    `USERNAME` VARCHAR(20) NOT NULL,
    `PASSWORD` VARCHAR(30) NOT NULL,
    `EMAIL` VARCHAR(50) NULL DEFAULT NULL,
    `ADMIN` BOOLEAN NOT NULL DEFAULT FALSE,
    `SCORE` INT NULL DEFAULT NULL,
    PRIMARY KEY(`ID`)
) ENGINE = InnoDB;
CREATE TABLE `caro`.`game`(
    `ID` VARCHAR(10) NOT NULL,
    `PLAYER_ID` VARCHAR(10) NOT NULL,
    `OPPONENT_NAME` VARCHAR(20) NULL DEFAULT NULL,
    `SCORE` INT NOT NULL DEFAULT '0',
    `GAME_TYPE` VARCHAR(10) NOT NULL,
    `DIFFICULTY` INT NOT NULL,
    `PLAY_TIME` INT NOT NULL,
    `START_TIME` DATETIME NOT NULL,
    `STATUS` VARCHAR(10) NOT NULL,
    `DATA` JSON NOT NULL,
    `NEXTMOVE` BOOLEAN NULL DEFAULT NULL,
    PRIMARY KEY(`ID`),
    FOREIGN KEY(`PLAYER_ID`) REFERENCES `user`(`ID`)
) ENGINE = InnoDB;